package com.proyectofinal.fintech.infrastructure.input.rest.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Request DTO for creating a user.
 * ID is auto-generated by the backend — not accepted from the client.
 * Jakarta Validation annotations on record components are valid in Spring Boot 3+.
 */
public record CreateUserRequestDto(
        @NotBlank @Size(min = 2) String name,
        @NotBlank @Email String email
) {}
