server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: fintech-wallet

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.proyectofinal.fintech: DEBUG
